"""Fix: user table add column role

Revision ID: 2eac912c2ec9
Revises: ac1539d563aa
Create Date: 2023-07-18 15:42:57.422642

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "2eac912c2ec9"
down_revision = "ac1539d563aa"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    user_role = postgresql.ENUM("super_admin", "admin", "user", name="user_role")
    user_role.create(op.get_bind())
    op.add_column(
        "users",
        sa.Column(
            "role",
            sa.Enum("super_admin", "admin", "user", name="user_role"),
            server_default="user",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "role")
    # ### end Alembic commands ###
