"""add pages column in books table

Revision ID: 58469b2979de
Revises: a4b73d6f421c
Create Date: 2023-07-17 17:28:53.502957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58469b2979de'
down_revision = 'a4b73d6f421c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('pages', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'pages')
    # ### end Alembic commands ###
